### ISSUE TITLE
Import and Adapt RL Extractive Summarization Code

### ISSUE THREAD

**Issue by jmsalvador2395** [jmsalvador2395/ml-toolkit#4]
# OVERVIEW
The current rl_extractive summarization code is a bit of a nightmare to work with so I am instead going to pull it into this project and adapt it accordingly. 

I have 2 main goals for this task:
1. **Clean up the code and break them up into appropriate sub-packages**. The current state of the [current project](https://github.com/bnaman50/[sofsat_rl_extractive](https://github.com/bnaman50/sofsat_rl_extractive)) is not ideal for me since it is not my original code and is not structured it in a way that makes sense to me
2. **Figure out all aspects of this project**. While working on the project I did not touch certain aspects of it so importing all the important parts into my repository will allow me to get a view of everything that is going on.

# TODO
- [x] import RLModel
- [x] adapt data module
- [ ] adapt reward model
    - [ ] put reward computation into reward model class instead of putting it all in the trainer
- [ ] finish training loop

# PROGRESS NOTES
* Batches are loaded properly to the train_step() function
* Forward pass for RLModel works and actions are being computed

# ISSUES?
* Sentences are shuffled during the __getitem__ step. seems like a mistake
